name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Add host key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        echo "Starting deployment to VPS..."
        ssh -v ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ~/hyperlipidemia_web && git pull origin main && bash scripts/deploy_hyperlipidemia.sh"
        echo "Deployment completed."