name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements/web.txt

    - name: Restart service
      run: |
        cd ~/hyperlipidemia_web
        git pull origin main
        ./scripts/deploy_hyperlipidemia.sh